# Generated by Django 5.2.5 on 2025-09-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('stop_type', models.CharField(choices=[('loading', 'Loading'), ('unloading', 'Unloading')], max_length=10)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_company', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('goods_description', models.TextField()),
                ('goods_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('goods_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('goods_type', models.CharField(choices=[('standard', 'Standard'), ('fragile', 'Fragile'), ('hazmat', 'Hazardous Materials'), ('refrigerated', 'Refrigerated'), ('oversized', 'Oversized')], default='standard', max_length=20)),
                ('special_instructions', models.TextField(blank=True)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_pickup_date', models.DateField(blank=True, null=True)),
                ('requested_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='orders.stop')),
                ('pickup_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_orders', to='orders.stop')),
            ],
        ),
    ]
