# Generated by Django 5.2.5 on 2025-09-08 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_stop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_stop',
        ),
        migrations.AddField(
            model_name='stop',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=10),
        ),
    ]
