# Generated by Django 5.2.5 on 2025-09-08 16:47

from django.db import migrations


def update_stop_types(apps, schema_editor):
    """Update stop types from loading/unloading to pickup/delivery"""
    Stop = apps.get_model('orders', 'Stop')

    # Update 'loading' to 'pickup'
    Stop.objects.filter(stop_type='loading').update(stop_type='pickup')

    # Update 'unloading' to 'delivery'
    Stop.objects.filter(stop_type='unloading').update(stop_type='delivery')


def reverse_update_stop_types(apps, schema_editor):
    """Reverse operation - update back to loading/unloading"""
    Stop = apps.get_model('orders', 'Stop')

    # This is a simplified reverse - we can't perfectly determine which
    # pickup stops should become loading vs which were originally pickup
    Stop.objects.filter(stop_type='pickup').update(stop_type='loading')
    Stop.objects.filter(stop_type='delivery').update(stop_type='unloading')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_delivery_stop_remove_order_pickup_stop_and_more'),
    ]

    operations = [
        migrations.RunPython(update_stop_types, reverse_update_stop_types),
    ]
