# Generated by Django 5.2.5 on 2025-09-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
