# Generated by Django 5.2.5 on 2025-09-03 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed', models.DecimalField(decimal_places=2, help_text='Speed in km/h', max_digits=5)),
                ('heading', models.DecimalField(decimal_places=2, help_text='Heading in degrees (0-360)', max_digits=5)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Altitude in meters', max_digits=8, null=True)),
                ('timestamp', models.DateTimeField(help_text='Timestamp when position was recorded')),
                ('odometer', models.DecimalField(blank=True, decimal_places=2, help_text='Odometer reading in km', max_digits=10, null=True)),
                ('fuel_level', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel level percentage (0-100)', max_digits=5, null=True)),
                ('engine_status', models.CharField(choices=[('on', 'Engine On'), ('off', 'Engine Off'), ('idle', 'Engine Idle')], default='off', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='positions_p_vehicle_eb1834_idx'), models.Index(fields=['timestamp'], name='positions_p_timesta_e1cfba_idx')],
            },
        ),
    ]
