# Generated by Django 5.2.5 on 2025-09-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('trips', '0002_stop_latitude_stop_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstop',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stops', to='orders.stop'),
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
    ]
