# Generated by Django 5.2.5 on 2025-09-11 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0003_alter_tripstop_stop_delete_stop"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tripstop",
            options={"ordering": ["sequence"]},
        ),
        migrations.RenameField(
            model_name="tripstop",
            old_name="order",
            new_name="sequence",
        ),
        migrations.AlterUniqueTogether(
            name="tripstop",
            unique_together={("trip", "sequence")},
        ),
    ]
